name: cluster-autoscaler
namespace: kube-system
serviceType: managed

# Make sure to update the docs at https://github.com/giantswarm/docs if you change the defaults below!
configmap:
  scaleDownUtilizationThreshold: 0.65

image:
  registry: quay.io
  repository: giantswarm/cluster-autoscaler
  tag: v1.13.1

cluster:
  id: "test-cluster"
