name: cluster-autoscaler
namespace: kube-system
serviceType: managed

userID: 65534
groupID: 65534

port: 8085

# Make sure to update the docs at https://github.com/giantswarm/docs/blob/master/src/layouts/shortcodes/autoscaler_utilization_threshold.html if you change the defaults below
configmap:
  expander: "least-waste"
  scanInterval: "10s"
  scaleDownUtilizationThreshold: 0.65
  skipNodesWithLocalStorage: "false"
  skipNodesWithSystemPods: "true"

image:
  registry: quay.io
  repository: giantswarm/cluster-autoscaler
  tag: v1.14.3

cluster:
  id: "test-cluster"
