name: cluster-autoscaler
namespace: kube-system
serviceType: managed

aws:
  region: "eu-central-1"

image:
  registry: quay.io
  repository: giantswarm/cluster-autoscaler
  tag: v1.12.1

cluster:
  id: "test-cluster"
