name: cluster-autoscaler
namespace: kube-system
serviceType: managed


configmap:
  utilizationThreshold: 0.65

image:
  registry: quay.io
  repository: giantswarm/cluster-autoscaler
  tag: v1.13.1

cluster:
  id: "test-cluster"
