apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    app: {{ .Values.name }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: "metrics"
    port: 8085
    protocol: TCP
